### PR TITLE
Added more dynamic options and autodetects

### PR DESCRIPTION
**Pull request by krazynez**
* Added ARK-4 Support
* Added Packages ( Searches PSP/GAME/ ISO/ PSP/GAME150 )
* Auto detect CPU/Bus Speed
* Added Memory in use

### CODE REVIEW

**Comment by krazynez** [comment]
~~Hang on don't merge this yet. I need to fix something still.~~  Good now


pic_0000

**Comment by entitybtw** [comment]
that's cool, thank u

**Comment by entitybtw** [comment]
@krazynez strange, it not works on ppsspp or psp

**Comment by entitybtw** [comment]
bad argument #1 to 'ipairs'

**Comment by krazynez** [comment]
> bad argument #1 to 'ipairs'

Oh you know what ipairs doesn't like null values scan dir needs to check if null before the loop https://github.com/entitybtw/pspfetch/blob/850e93e3592ffdc4c17b74c6a1b8259430eaceb0/pspfetch.lua#L140 . I get home later today unless you want to add the check real quick.

**Comment by entitybtw** [comment]
> bad argument #1 to 'ipairs'

one lua error

**Pull request merged**
